PROJECTED_CRS_SRID = 2154
WAYPOINT_MOTORWAY_DISTANCE_THRESHOLD = 1  # Maximum distance to attach a motorway element to the route in meter

# Fuel consumptions in l/100km
CONSUMPTION_REDUCTION_FACTOR_110_130 = 0.25
DEFAULT_NON_MOTORWAY_CONSUMPTION = 6
DEFAULT_MOTORWAY_130KMH_CONSUMPTION = 6
DEFAULT_MOTORWAY_110KMH_CONSUMPTION = (1 - CONSUMPTION_REDUCTION_FACTOR_110_130) * DEFAULT_MOTORWAY_130KMH_CONSUMPTION
